logging:
  level:
    com.ylz.ai.mobile: DEBUG
spring:
  application:
    name: ai-mobile
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: ylz_ai
    url: jdbc:mysql://localhost:3306/ylz_ai?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # redis 配置
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 8   # 最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     # 最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     # 最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: 123456
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /ylz-ai
    username: admin
    password: admin
    publisher-confirms: true
    publisher-returns: true
    #采用手动应答
    listener:
      simple:
        acknowledge-mode: manual
  zipkin:
    enabled: true
  sleuth:
    sampler:
      percentage: 1

server:
  port: 8763

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

# mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 4
      # 默认数据库表下划线命名
      table-underline: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  threadpool:
    default:
      coreSize: 1000 # 并发执行的最大线程数，默认10
      maxQueueSize: 1000 # BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

auth:
  serviceId: ai-auth
  user:
    token-header: Authorization
  client:
    id: ai-mobile
    secret: 123456
    token-header: client-token

request:
  skip: /druid/**,/swagger-ui.html,/doc.html,/v2/**,/webjars/**,/swagger**/**,/,/csrf,/error

swagger:
  # 配置请求路由
  zuul:
    host: localhost:8765
    prefix: /api/mobile
  production: false
  basic:
    enable: false
    username: admin
    password: admin

weixin:
  appid: wx578b4454700f0a35
  secret: a9d765b57060b8e276a64567205325bd
  grant_type: authorization_code

upload:
  path: /opt/picture